sudo: false
language: ruby
rvm:
- 2.3.4
- 2.4.1
cache: bundler
bundler_args: "--without production"
before_install: gem install bundler
script:
- bundle exec rspec
branches:
  only:
  - master
notifications:
  email: false
  slack:
    secure: zKuPqW7/Ssx10LGQzMoxDU8rzmbFq4a/0fo8tkmu0CJaW3eUvqpwRn9dcxYvQ7UhGkFHU/BVEOT9AazlBKAm4+Fn5sC/YJQjFhWVa9KHFr4vjl+Ns109cMY/wMS4FRrjz2C2vFPBeMfeBBvf8qIgnYiFfy9YiotqGG2wqVeCgoIlsvdD2jRDzI7zvQkmUzBnlZ5JGKsR1USPUV5PZRMb6jQ5Qy6m/kTn50cyMog329wrsgDP8JKDjEE/8hQpOPh/Bxdf9wTJ80MajcORHbbxfq16BeMqH5C5Yu8SzndoOG3jn0YT7+J7xvG6VU1Ydsxkj6ypKiwH9obGLjd3azambiOujTTc0FzXhnAW5EdkJTmCw7UhzqjPQNXyaZalacyIB3mAUxkXcLUAHdVxYcOy1GoPy2A+98lVAvE7JyOBZmQjfjrsPhja2cFgUPiQfh/QQIu1nerLepRJLR5oBLl90TUi4gLPYgmLqs34mB55lRN2pCnvHPhwwsk0tot9bYalKNGA7A6OY7GJdQ9xv2rfhgayAvgIWiwWvqd6q22eXQVBjinKZCile92DDOg8u+xzQ8Z6djq3EHFQs6Gs0H4u0CPUjK6/8ELHCn3ICyIpoKIetjjmfbImDgZ9amT2m6lJhdRwIOKuL4A8/ci0mnLFkkRxDR/wnNiws3n9jmNISnY=
